apiVersion: batch/v1
kind: Job
metadata:
  name: loyalty-user-cleanup-utility
  labels:
    app: loyalty-user-cleanup-utility
spec:
  template:
    metadata:
      labels:
        app: loyalty-user-cleanup-utility
    spec:
      restartPolicy: Never
      containers:
      - name: loyalty-user-cleanup-utility
        image: us.icr.io/gregd/loyalty-user-cleanup-utility:1.0-SNAPSHOT
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: loyalty-db-secret
        - secretRef:
            name: loyalty-iam-secret
        - secretRef:
            name: loyalty-appid-secret
        env:
        - name: LAST_LOGIN_HOURS
          value: "24"
  backoffLimit: 0